In [1]:
import numpy as np

In [2]:
a = np.array([1])
a

array([1])

In [3]:
print(a)
a.shape

[1]


(1,)

In [4]:
b = np.array([[1.145]])
b.shape

(1, 1)

In [5]:
b.ndim

2

In [6]:
a.ndim

1

In [7]:
matrix = np.array([[1,2,3],[2,3,4]])
matrix

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

(2, 3)

In [10]:
# Create a 5x4 matrix
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
d[0]

array([1, 2, 3, 4])

In [11]:
d = matrix[0]
d

array([1, 2, 3])

In [12]:
d.ndim

1

In [13]:
d.shape

(3,)

In [14]:
# Extract through 
d = matrix[:][1]
d

array([2, 3, 4])

In [15]:
d.ndim

1

In [16]:
a = np.zeros((3,3))
b = np.ones((2,3))
y = np.vstack((a,b))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
y = np.zeros((3,3)),np.ones((2,3))
y

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [18]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
# b = np.array([a[0,0],a[1,1],a[2,2]])
# b
b = (a[[0,1,2] ,[0,1,2]])
b
b.ndim

1

In [19]:
t = np.array([a[[0,1,2],[2,1,2]]])
t.ndim

2

In [20]:
A = np.array([[10,-2,1,0],[3,5,-7,22],[4,-1,-3,16],[0,5,8,-9]])
A

array([[10, -2,  1,  0],
       [ 3,  5, -7, 22],
       [ 4, -1, -3, 16],
       [ 0,  5,  8, -9]])