# Numpy Arrays
## Contents

- [Array_Creation_Methods](#creation)
- [Copying](#copying)
- [Casting](#casting)
- [Nan](#nan)
- [Infinity](#infinity)



#  Creation 
1. np.empty
2. np.zeros
3. np.ones
4. np.arange
5. np.linspace
6. np.array
7. np.random.rand
8. np.random.randn

## numpy.empty <br>
np.empty(shape, dtype=float, order='C', *, like=None) <br>

* Return a new array of given shape and type, without initializing entries.
* empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.


In [1]:
import numpy as np

In [2]:
np.empty((2, 2))

array([[4.64089757e-310, 0.00000000e+000],
       [4.64089724e-310, 4.64089765e-310]])

In [3]:
np.empty([2, 2])

array([[4.64089757e-310, 0.00000000e+000],
       [4.64089724e-310, 4.64089765e-310]])

## numpy.zeros <br>
np.zeros(shape, dtype=float, order='C', *, like=None) <br>
- Return a new array of given shape and type, filled with zeros. <br>
- by default, numpy.zeros() creates an array with elements of type float. <br>

In [4]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [5]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [6]:
np.zeros((5,), dtype=int)


array([0, 0, 0, 0, 0])

In [7]:
np.zeros((2, 1))


array([[0.],
       [0.]])

## numpy.ones <br>
numpy.ones(shape, dtype=None, order='C', *, like=None)<br>
- Return a new array of given shape and type, filled with ones.<br>

In [8]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## numpy.arange
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
- Return evenly spaced values within a given interval.
- When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2, 10 , 2)

array([2, 4, 6, 8])

In [14]:
np.arange(0, 1, 0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9]

In [15]:
np.arange('2021-01-01', '2022-01-01', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
       '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
       '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
       '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
       '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
       '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
       '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
       '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
       '2021-03-02', '2021-03-03', '2021-03-04', '2021-

## nimpy.linspace
<pre>
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) returns
an array of evenly spaced numbers over a specified interval.

start: The starting value of the sequence.
stop: The end value of the sequence.
num: The number of evenly spaced values within the range. Default is 50.
endpoint: Whether to include the stop value in the sequence. Default is True.
retstep: Whether to return the spacing between samples. Default is False.
dtype: The data type of the output array. If not given, it is determined from the input parameters.
axis: The axis along which to generate the output array. Default is 0.

</pre>

In [16]:
np.linspace(9, 3, 5)

array([9. , 7.5, 6. , 4.5, 3. ])

## np.array
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
- Create an array.
- np.array() creates a new array object. If we modify the values in the original list or tuple used to create the array, the array itself will not be automatically updated. We would need to create a new array to reflect the changes.

In [17]:
arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [18]:
arr = np.array([0, 0.1, 2]) # Upcast to float type to avoid loss of precision in the conversion to integer type 
print(repr(arr))

array([0. , 0.1, 2. ])


## np.random.rand

Generate random numbers from a uniform distribution over [0, 1). <br>
<pre>
numpy.random.rand(d0, d1, ..., dn)
d0, d1, …, dn : int, optional
The dimensions of the returned array, should all be positive. If no argument is given 
a single Python float is returned.
</pre>

In [19]:
arr = np.random.rand(2, 5)
print(repr(arr))
print(arr.shape)

array([[0.83492519, 0.26534226, 0.02794835, 0.53092017, 0.97564241],
       [0.18205832, 0.58782219, 0.58782976, 0.72280077, 0.34540094]])
(2, 5)


## np.random.randn

Return a sample (or samples) from the “standard normal” distribution. <br>
<pre>
numpy.random.randn(d0, d1, ..., dn)
d0, d1, …, dn : int, optional
The dimensions of the returned array, should all be positive. If no argument is given
a single Python float is returned.
</pre>

In [20]:
arr = np.random.randint(0, 10, (2, 3))
print(repr(arr))

array([[5, 6, 7],
       [8, 5, 5]])


# Copying

1. Shallow Copy (View): A shallow copy creates a new array object that points to the same data as the original array. Any changes made to the new array will be reflected in the original array as well. NumPy provides a view() method to create a shallow copy of an array.
2. Deep Copy: A deep copy creates a new array object with new data and the original data is copied into it. Any changes made to the new array will not be reflected in the original array. NumPy provides a copy() method to create a deep copy of an array.

In [23]:
import numpy as np

# create an array
arr = np.array([1, 2, 3])

# shallow copy (view) of the array
arr_view = arr.view()

# deep copy of the array
arr_copy = arr.copy()

# modify the view and copy arrays
arr_view[0] = 10
arr_copy[0] = 100

# print the original array and the copies
print(arr)       # Output: [10  2  3]
print(arr_view)  # Output: [10  2  3]
print(arr_copy)  # Output: [100   2   3]
print(arr)


[10  2  3]
[10  2  3]
[100   2   3]
[10  2  3]


# Casting

It means converting the data type of an array from one to another. We can use the astype() method to cast an array to a specific type.

In [25]:
arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


# Nan

- When we don't want a NumPy array to contain a value at a particular index, we can use np.nan to act as a placeholder.
- A common usage for np.nan is as a filler value for incomplete data.
- The code below shows an example usage of np.nan.
- Note that np.nan cannot take on an integer type.

In [29]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError: If we uncomment line 8 and run again.
# np.array([np.nan, 1, 2], dtype=np.int32)
np.array([np.nan, 1, 2], dtype=np.float32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


array([nan,  1.,  2.], dtype=float32)

# Infinity

- We can use np.inf to represent positive infinity and -np.inf to represent negative infinity.
- The code below shows an example usage of np.inf and -np.inf.
- Note that np.inf cannot take on an integer type.

In [30]:
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# Will result in a OverflowError: If we uncomment line 10 and run again.
#np.array([np.inf, 3], dtype=np.int32)
np.array([np.inf, 3], dtype=np.float32)

True
array([inf,  5.])
array([-inf,   1.])


array([inf,  3.], dtype=float32)