# numpy.empty <br>
numpy.empty(shape, dtype=float, order='C', *, like=None) <br>

* Return a new array of given shape and type, without initializing entries.
* empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster. On the other hand, it requires the user to manually set all the values in the array, and should be used with caution.


In [3]:
import numpy as np

In [5]:
np.empty((2, 2))

array([[4.65286506e-310, 0.00000000e+000],
       [4.65286467e-310, 4.65286470e-310]])

In [8]:
np.empty([2, 2])

array([[4.65286521e-310, 0.00000000e+000],
       [4.65286481e-310, 4.65286480e-310]])

# numpy.zeros <br>
numpy.zeros(shape, dtype=float, order='C', *, like=None) <br>
- Return a new array of given shape and type, filled with zeros. <br>
- by default, numpy.zeros() creates an array with elements of type float. <br>

In [10]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [14]:
np.zeros((5,), dtype=int)


array([0, 0, 0, 0, 0])

In [16]:
np.zeros((2, 1))


array([[0.],
       [0.]])

# numpy.ones <br>
numpy.ones(shape, dtype=None, order='C', *, like=None)<br>
- Return a new array of given shape and type, filled with ones.<br>

In [17]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# numpy.arange
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
- Return evenly spaced values within a given interval.
- When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(2, 10 , 2)

array([2, 4, 6, 8])

In [28]:
np.arange(0, 1, 0.1).tolist()

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9]

In [32]:
np.arange('2021-01-01', '2022-01-01', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
       '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
       '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
       '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
       '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
       '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
       '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
       '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01',
       '2021-03-02', '2021-03-03', '2021-03-04', '2021-

# nimpy.linspace
<pre>
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) returns
an array of evenly spaced numbers over a specified interval.

start: The starting value of the sequence.
stop: The end value of the sequence.
num: The number of evenly spaced values within the range. Default is 50.
endpoint: Whether to include the stop value in the sequence. Default is True.
retstep: Whether to return the spacing between samples. Default is False.
dtype: The data type of the output array. If not given, it is determined from the input parameters.
axis: The axis along which to generate the output array. Default is 0.

</pre>

In [43]:
np.linspace(9, 3, 5)

array([9. , 7.5, 6. , 4.5, 3. ])

# np.array
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
- Create an array.
- np.array() creates a new array object. If we modify the values in the original list or tuple used to create the array, the array itself will not be automatically updated. We would need to create a new array to reflect the changes.

In [45]:
arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [46]:
arr = np.array([0, 0.1, 2]) # Upcast to float type to avoid loss of precision in the conversion to integer type 
print(repr(arr))

array([0. , 0.1, 2. ])
